
name: Swift Lint

on:
  workflow_call:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --force-exclude

